#ifndef __Uniform4fEditorUniform4fEditor__
#define __Uniform4fEditorUniform4fEditor__

/**
@file
Subclass of Uniform4fEditor, which is generated by wxFormBuilder.
*/

#include "Uniform4fEditorBase.h"

//// end generated include

#include "ViewerMainFrame.h"

/** Implementing Uniform4fEditor */
class Uniform4fEditorUniform4fEditor : public Uniform4fEditor
{
	protected:
		// Handlers for Uniform4fEditor events.
		void m_spinCtrlDoubleXRSOnSpinCtrlDouble( wxSpinDoubleEvent& event );
		void m_spinCtrlDoubleXRSOnTextEnter( wxCommandEvent& event );
	public:
		/** Constructor */
		Uniform4fEditorUniform4fEditor( wxWindow* parent );
	//// end generated class members









};

#endif // __Uniform4fEditorUniform4fEditor__
