#ifndef __ViewerMainFrame__
#define __ViewerMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "ViewerBase.h"

//// end generated include

/** Implementing MainFrame */
class ViewerMainFrame : public MainFrame
{
	public:
		/** Constructor */
		ViewerMainFrame( wxWindow* parent );
	//// end generated class members










};

#endif // __ViewerMainFrame__
