#ifndef __ViewerMainFrame__
#define __ViewerMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "ViewerBase.h"

//// end generated include

#include "GLCanvas.h"
#include "IEngine.h"

/** Implementing MainFrame */
class ViewerMainFrame : public MainFrame
{
	public:
		/** Constructor */
		ViewerMainFrame( wxWindow* parent );
	//// end generated class members

private:
	Viewer::IEngineSPtr m_spEngine;
	wxGLCanvas* m_GlCanvas;













};

#endif // __ViewerMainFrame__
