#ifndef __ViewerMainFrame__
#define __ViewerMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "ViewerBase.h"

//// end generated include

#include "GLCanvas.h"
#include "IEngine.h"
#include "wx/timer.h"
#include "Uniform4fEditorUniform4fEditor.h"

/** Implementing MainFrame */
class ViewerMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void m_menuUniform4fOnMenuSelection( wxCommandEvent& event );
	public:
		/** Constructor */
		ViewerMainFrame( wxWindow* parent );
	//// end generated class members

		~ViewerMainFrame();
		Viewer::IEngineSPtr GetEngine();
		wxGLCanvas* GetGLCanvas();

private:
	Viewer::IEngineSPtr m_spEngine;
	wxGLCanvas* m_GLCanvas;
	wxTimer m_Timer;
};

#endif // __ViewerMainFrame__
